- !include automation/alarm_set_away.yaml
- !include automation/alarm_trigger.yaml
- !include automation/alarm_set_home.yaml
- !include automation/check_for_update.yaml

#location based
- !include automation/away.yaml

#sensor based
- !include automation/humidity_high.yaml
- !include automation/humidity_low.yaml
- !include automation/alarm_clock.yaml
- !include automation/cubesensors_battery.yaml
- !include automation/cubesensors_battery_dnevna.yaml
- !include automation/badair_dnevna.yaml
- !include automation/badair_spalnica.yaml

#input based
- !include automation/sleep_mode.yaml
- !include automation/livingroom_light.yaml
- !include automation/radiostation.yaml
- !include automation/siol_channel.yaml
- !include automation/siol_input_tv_slo_1.yaml
- !include automation/siol_input_tv_slo_2.yaml
- !include automation/siol_input_pop_tv.yaml
- !include automation/siol_input_kanal_a.yaml
- !include automation/siol_input_discovery.yaml
- !include automation/siol_input_id.yaml
- !include automation/siol_input_ng.yaml
- !include automation/siol_input_rtl.yaml
- !include automation/siol_input_none.yaml

#sun based
#- !include automation/sleep_mode_off.yaml
#- !include automation/sun_notifications.yaml

#media player
- !include automation/media_bedroom_pause.yaml
- !include automation/media_bedroom_play.yaml
- !include automation/media_bedroom_off.yaml
- !include automation/media_livingroom_play.yaml
- !include automation/media_living_room_pause.yaml
- !include automation/media_bedroom_on.yaml
- !include automation/media_living_room_on.yaml

#thermostat based
- !include automation/pec_on.yaml
- !include automation/pec_off.yaml

#ir remote based
- !include automation/remote_music.yaml

#time base
- !include automation/alarm_weekend.yaml
- !include automation/alarm_weekdays.yaml
