#- platform: bluetooth_tracker
#- platform: nmap_tracker
#  hosts: 192.168.0.1/24
#  home_interval: 3
#  consider_home: 300
#  track_new_devices: yes
#- platform: bluetooth_tracker
#- platform: locative
- platform: ios
