- platform: kodi
  host: !secret kodi_bedroom_ip
  port: 8080
  name: Bedroom Kodi

- platform: kodi
  host: !secret kodi_livingroom_ip
  port: 8080
  name: Living room Kodi

- platform: mpd
  host: 127.0.0.1
  port: 6600
  location: Living Room Radio

- platform: panasonic_viera
  host: !secret panasonic_tv_ip
  port: 55000
  name: Living Room TV

#- platform: denon_avr
#  host: !secret denon_ip
#  name: Denon AVR

- platform: denonavr
  host: !secret denon_ip
  name: Denon AVR

- platform: universal
  name: Siol BOX
  children:
    - media_player.siol_box
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.siol_box
    turn_off:      
      service: switch.turn_off
      data:
        entity_id: switch.siol_box
  attributes:
    state: switch.siol_box
