alias: 'Alarm clock for weekends'
trigger:
  platform: time
  minutes: '/30'
  seconds: 0
condition: 
  condition: time
  weekday:
    - sat
    - sun
action:
  - service: input_slider.select_value
    data:
      entity_id: input_slider.alarmhour
      value: '8'
  - service: input_slider.select_value
    data:
      entity_id: input_slider.alarmminutes
      value: '30'
