alias: 'Alarm clock for weekdays'
trigger:
  platform: time
  minutes: '/30'
  seconds: 0
condition: 
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  - service: input_slider.select_value
    data:
      entity_id: input_slider.alarmhour
      value: '6'
  - service: input_slider.select_value
    data:
      entity_id: input_slider.alarmminutes
      value: '45'
