alias: "Pec on"
trigger:
  - platform: template
    value_template: "{% if is_state_attr('climate.thermostat', 'operation_mode', 'heat') %}true{% endif %}"
action:
  - service: switch.turn_on
    entity_id: switch.glavno_stikalo_peci
  - service: notify.ios_iphone
    data:
      message: "Burner has turned on."
      title: "Burner turning on"
