alias: "Pec off"
trigger:
  - platform: template
    value_template: "{% if is_state_attr('climate.thermostat', 'operation_mode', 'idle') %}true{% endif %}"
action:
  - service: switch.turn_off
    entity_id: switch.glavno_stikalo_peci
  - service: notify.ios_iphone
    data:
      message: "Burner has turned off."
      title: "Burner turning off"
