alias: "Siol tv slo 2"
trigger:
  platform: state
  entity_id: 'input_select.siol_box_channel_name'
  to: "TV SLO 2"
action:
  service: input_select.select_option
  data:
    entity_id: input_select.siol_box_channel
    option: "2"
