alias: "Siol national geographic"
trigger:
  platform: state
  entity_id: 'input_select.siol_box_channel_name'
  to: "National Geographic"
action:
  service: input_select.select_option
  data:
    entity_id: input_select.siol_box_channel
    option: "101"
