alias: "Siol none"
trigger:
  platform: state
  entity_id: 'input_select.siol_box_channel_name'
  to: "None"
action:
  service: input_select.select_option
  data:
    entity_id: input_select.siol_box_channel
    option: "None"
