alias: "Siol discovery id extra"
trigger:
  platform: state
  entity_id: 'input_select.siol_box_channel_name'
  to: "Discovery ID Extra"
action:
  service: input_select.select_option
  data:
    entity_id: input_select.siol_box_channel
    option: "93"
