alias: "Siol Channel"
trigger:
  - platform: state
    entity_id: input_select.siol_box_channel
action:
  - service: shell_command.siol_channel
  - service: media_player.select_source
    data:
      entity_id: media_player.denon_avrx2200w
      source: "CBL/SAT"
