alias: 'Send notification when sun rises'
trigger:
  platform: sun
  event: sunrise
  offset: '+00:00:00'
action:
  service: notify.ios_iphone
  data:
    message: 'The sun is up.'
alias: 'Send notification when sun sets'
trigger:
  platform: sun
  event: sunset
  offset: '+00:00:00'
action:
  service: notify.ios_iphone
  data:
    message: 'The sun is down.'
